-- ============================================
-- VideoBee Database Schema for Supabase
-- ============================================
-- This SQL sets up the rooms table with permissive RLS policies
-- for tracking room existence and cleanup without authentication
-- ============================================

-- Create the rooms table
CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    active BOOLEAN DEFAULT true NOT NULL,
    last_activity TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create an index on room_code for faster lookups
CREATE INDEX IF NOT EXISTS idx_rooms_room_code ON rooms(room_code);

-- Create an index on active status for cleanup queries
CREATE INDEX IF NOT EXISTS idx_rooms_active ON rooms(active);

-- Create an index on last_activity for identifying stale rooms
CREATE INDEX IF NOT EXISTS idx_rooms_last_activity ON rooms(last_activity);

-- Enable Row Level Security
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;

-- Create permissive RLS policies (no authentication required)
-- Allow anyone to insert rooms (for room creation)
CREATE POLICY "Allow public room creation"
    ON rooms
    FOR INSERT
    TO anon
    WITH CHECK (true);

-- Allow anyone to view rooms (for checking if a room exists)
CREATE POLICY "Allow public room viewing"
    ON rooms
    FOR SELECT
    TO anon
    USING (true);

-- Allow anyone to update rooms (for marking inactive or updating activity)
CREATE POLICY "Allow public room updates"
    ON rooms
    FOR UPDATE
    TO anon
    USING (true)
    WITH CHECK (true);

-- Optional: Function to clean up inactive rooms older than 24 hours
CREATE OR REPLACE FUNCTION cleanup_inactive_rooms()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM rooms
    WHERE active = false
    AND last_activity < NOW() - INTERVAL '24 hours';
END;
$$;

-- Optional: Function to mark rooms as inactive if no recent activity
-- This would typically be called by a cron job or when participants leave
CREATE OR REPLACE FUNCTION mark_stale_rooms_inactive()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE rooms
    SET active = false
    WHERE active = true
    AND last_activity < NOW() - INTERVAL '1 hour';
END;
$$;

-- Optional: Create a trigger to update last_activity on room updates
CREATE OR REPLACE FUNCTION update_last_activity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.last_activity = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_update_last_activity
    BEFORE UPDATE ON rooms
    FOR EACH ROW
    EXECUTE FUNCTION update_last_activity();

-- ============================================
-- NOTES:
-- ============================================
-- 
-- 1. The rooms table is optional for basic functionality since
--    Supabase Realtime Presence handles participant tracking.
--    This table is mainly for:
--    - Room existence validation
--    - Room cleanup and maintenance
--    - Analytics (if you want to track room usage)
--
-- 2. The RLS policies are permissive (WITH CHECK (true)) because
--    VideoBee has no authentication system. In production with auth,
--    you would want to restrict these policies based on user identity.
--
-- 3. To set up automatic cleanup, you can:
--    - Use Supabase's pg_cron extension to schedule cleanup functions
--    - Call these functions from your application when participants leave
--    - Manually run cleanup queries via the Supabase dashboard
--
-- 4. For the free tier, consider:
--    - Running cleanup manually or less frequently
--    - Adding a max_participants limit to prevent abuse
--    - Monitoring the database size in the Supabase dashboard
--
-- ============================================